Added wait and retries for rate limit response code from Bitbucket server
jenkinsci/bitbucket-branch-source-plugin pull request #433
Opened 2021-03-02 08:38 UTC by shankarinece

Added 5 seconds wait and retry the same API if Bitbucket responds with rate-limit response code (429). Relates to JENKINS-62479, 

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

2021-04-16 14:29 UTC, ryancurrah commented
This is a really handy improvement that would be beneficial for everyone.

2021-05-10 00:47 UTC, Zauxst commented
@bitwiseman , are you in charge of merging PRs?  
Can you take a look over this one? 

The rate API is quite important to be fixed especially in large organizations…
Also, Bitbucket does not have any response headers regarding RATE API as mentioned in #414

2021-05-10 05:31 UTC, tarioch commented
If you have many open prs, #445 might be important for you as well, on our setup it reduced the number of api calls massively

2021-07-15 15:23 UTC, bitwiseman requested changes
This is great start! Please address the comments and add some tests of the behavior.

2021-07-15 15:23 UTC, bitwiseman commented on src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
> +                Thread.sleep(API_RATE_LIMIT_WAIT_TIME_DEFAULT);
Just waiting for 5 seconds will cause a lot of polling and spamming of the server. Please shift to some kind of progressive back off where each of retry waits longer (up to some reasonable limit. 

Alternative: see if they the headers of the 429 provide information about when to the limit will reset and sleep for something like that long.

2021-07-19 19:40 UTC, bitwiseman commented
See #414

2021-09-03 19:51 UTC, smirkybg commented
Can we get some progress on this? I'm constantly hitting 429 on our Jenkins setup and we definitely welcome this rate limit progressive back off strategy.

2022-04-05 00:28 UTC, lifeofguenter commented
Closing in favor of https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/581

2022-04-05 00:28 UTC, closed without merging