JENKINS-66040: fix in-progress notifications for non-standard project recognizers
jenkinsci/bitbucket-branch-source-plugin pull request #463
Opened 2021-07-03 10:50 UTC by dee-kryvenko

See https://issues.jenkins.io/browse/JENKINS-66040

### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

2021-07-08 01:09 UTC, bitwiseman requested changes
Please add a test that verifies this change.

2021-07-08 07:49 UTC, dee-kryvenko commented
@bitwiseman that wasn't easy for a beginner to figure out given no tests previously existed for this piece of functionality - but I think I pulled it off. Hopefully that will do.

2021-07-19 18:36 UTC, bitwiseman approved these changes

2021-07-19 18:37 UTC, bitwiseman commented
@dee-kryvenko 
Great job figuring out tests!

2021-07-23 09:08 UTC, merged

2021-07-23 09:28 UTC, dee-kryvenko commented
Thanks @bitwiseman !

2026-08-28 01:57 UTC, jglick commented on src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTest.java
> +        assertThat((List<Action>) run.getAllActions(), not(hasItem(instanceOf(FirstCheckoutCompletedInvisibleAction.class))));
This is failing with https://github.com/jenkinsci/workflow-multibranch-plugin/pull/582 but I cannot figure out what the purpose of this assertion (and test case) is. https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/130 as written seems to make sense, and so does the main source code change here, but what is the test supposedly proving?